
services:
  jenkins:
    build:
      context: jenkins
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - NO_PROXY="dind;${NO_PROXY}"
      - no_proxy="dind;${no_proxy}"
    volumes:
      - cert:/certs/client
      - data:/var/jenkins_home
    ports:
      - 9001:8080
      - 50000:50000
    networks:
      - default
    depends_on:
      - dind

  dind:
    image: docker.io/docker:dind
    hostname: dind
    restart: unless-stopped
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    command: --storage-driver overlay2
    volumes:
      - cert:/certs/client
      - data:/var/jenkins_home
      - docker:/var/lib/docker
    networks:
      - default

volumes:
  cert:
  data:
  docker:

networks:
  default: